'use strict';
const $=id=>document.getElementById(id);
const names={user:'User',parent:'Parent',worker:'Subagent',tools:'Tools',native:'RDD engine',memory:'Engram'};
const positions={user:[150,10],parent:[150,95],worker:[20,190],native:[280,190],tools:[20,285],memory:[280,285]};
const links=[['user','parent'],['parent','worker'],['parent','native'],['parent','tools'],['parent','memory'],['worker','tools'],['worker','native'],['native','memory']];
const esc=t=>String(t??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let total=0,timer,steps=[],cursor=0,waiting=false,seen=new Set();
function graph(from,to){
 const all=links.some(([a,b])=>a===from&&b===to||a===to&&b===from)||from===to?links:[...links,[from,to]];
 $('graph').innerHTML=all.map(([a,b])=>{const [x,y]=positions[a],[u,v]=positions[b];const d=`M${x+60} ${y+24} L${u+60} ${v+24}`,active=a===from&&b===to||a===to&&b===from;return `<path class="edge ${active?'active':''}" d="${d}"/>${active&&!matchMedia('(prefers-reduced-motion: reduce)').matches?`<circle class="packet" r="4"><animateMotion dur="1.1s" repeatCount="indefinite" path="${d}" ${a===from?'':'keyPoints="1;0" keyTimes="0;1" calcMode="linear"'}/></circle>`:''}`}).join('')+Object.entries(positions).map(([k,[x,y]])=>`<g class="${k===from||k===to?'active':''}"><rect x="${x}" y="${y}" width="120" height="48" rx="7"/><text x="${x+60}" y="${y+29}" text-anchor="middle">${names[k]}</text></g>`).join('');
}
function append(e){
 if(e.id&&seen.has(e.id))return;if(e.id)seen.add(e.id);
 if(seen.size>1000)seen.delete(seen.values().next().value);
 if(!total)$('log').textContent='';total++;
 const row=document.createElement('article');row.className=`event ${e.from==='user'?'user':''} ${e.from==='worker'||e.to==='worker'?'worker':''} ${e.status==='error'?'error':''}`;
 row.innerHTML=`<h3>${esc(e.title)}<span>${esc(e.status??'observed')}</span></h3><p>${esc(e.text)}</p>${e.details?`<details><summary>Contract and evidence</summary><pre>${esc(JSON.stringify(e.details,null,2))}</pre></details>`:''}`;
 $('log').append(row);while($('log').children.length>200)$('log').firstChild.remove();$('log').scrollTop=$('log').scrollHeight;
 graph(e.from,e.to);$('handoff').textContent=`${names[e.from]} → ${names[e.to]}`;$('phase').textContent=e.phase??e.status??'OBSERVED';$('time').textContent=e.time?new Date(e.time).toLocaleTimeString():'SCRIPTED EXAMPLE';$('count').textContent=`${total} events`;
 if(e.from==='user')$('prompt').textContent=e.text;
 if(e.from==='worker'||e.to==='worker')$('child').textContent=[e.taskId?`Task: ${e.taskId}`:'',e.title,e.text].filter(Boolean).join('\n');
 if(e.status==='interaction_required')$('prompt').textContent='Waiting for a human decision. Reply in the Gentle terminal.';
 return row;
}
const ev=(from,to,title,text,phase='ODD',extra={})=>({from,to,title,text,phase,status:'illustrative',...extra});
const demos=[
 [ev('user','parent','User request','Fix “Export flie” in the report help.'),ev('parent','tools','Inspect the existing text','Read the help file and inspect its diff.'),ev('tools','parent','Bounded change','One documentation typo. No executable behavior changes.'),ev('parent','tools','Edit the word','Export flie → Export file'),ev('native','parent','Review assessment','Passive change; inspect the content. No review perspectives needed.','RDD'),ev('parent','user','Result','Corrected the typo and checked the diff. No artificial delegation or questions.')],
 [ev('user','parent','User request','Add CSV export using the current report workflow.'),ev('parent','worker','Delegate exploration','Map filters, permissions and export integration points. Read only.'),ev('worker','parent','Exploration result','Two valid export scopes exist. Product intent must choose one.'),ev('parent','memory','Record intent','Save the ODD task document and its Engram mirror.'),ev('parent','worker','Delegate implementation','Keep existing permissions. Use configured TDD and the targeted runner.'),ev('worker','parent','Worker asks the parent','Should export contain filtered rows or all accessible rows?','ODD',{status:'interaction_required'}),ev('parent','user','Choose the export scope','The parent relays the product decision to the user.','ODD',{question:true}),ev('parent','worker','Resume with confirmed scope','Read the updated ODD contract before implementing.'),ev('worker','tools','RED','Write and run a failing CSV test. Confirm failure is caused by missing behavior.','TDD'),ev('tools','worker','GREEN','Implement the minimum behavior. Run the same targeted test.','TDD'),ev('worker','tools','TRIANGULATE / REFACTOR','Check quoting, empty rows and permissions; refactor with green tests.','TDD'),ev('worker','parent','agent_end','Response received; settlement is still pending.','TDD',{status:'awaiting settlement'}),ev('worker','parent','agent_settled','Deliver structured result and focused validation evidence.','TDD',{status:'settled'}),ev('native','parent','Review checkpoint','Follow the native candidate identity and applicable consent.','RDD'),ev('parent','user','Result','Export is implemented and the observed checks are reported. Publishing requires its own authorization.')],
 [ev('user','parent','User request','Users from tenant A can access reports from tenant B. Fix isolation.'),ev('parent','worker','Bound the fix','Document isolation criteria; delegate only the authorized surfaces.'),ev('worker','tools','Reproduce and fix','RED reproduces cross-tenant access. GREEN checks the tenant. Add alternate cases.','TDD'),ev('worker','parent','Return evidence','Return the scoped patch and test results.'),ev('native','worker','Four review perspectives','Risk, Resilience, Readability and Reliability inspect the same frozen candidate.','RDD'),ev('worker','native','Finding','The cache key omits the tenant. Reproduction evidence supports the claim.','RDD'),ev('native','worker','Refute the claim','Check the allegation against the actual candidate and evidence.','RDD'),ev('parent','worker','Bounded remediation','Add tenant identity to the cache key and a regression test.','RDD'),ev('worker','tools','Regression check','Reproduce two tenants with the same report ID; fix and rerun.','TDD'),ev('native','parent','Directed validation and ACK','Validate the original criterion and repair regressions. Consume native authority.','RDD'),ev('parent','user','Result','Isolation and the cache key are corrected. Review approval does not authorize publication.')],
 [ev('user','parent','User request','Continue yesterday’s export. Keep TDD disabled and use configured checks.'),ev('parent','memory','Recover task context','Read the ODD document and attempt memory retrieval.'),ev('memory','parent','Memory unavailable','Do not claim that the Engram mirror is synchronized.','ODD',{status:'error'}),ev('parent','tools','Inspect actual state','Read the repository, task document and existing evidence.'),ev('parent','worker','Relaunch bounded work','Pass recovered intent and current constraints. Do not invent an active child session.'),ev('worker','tools','Configured verification','Run the configured build and focused checks; do not label this as RED/GREEN TDD.'),ev('worker','parent','Return result','Return validation evidence and mark the memory mirror as pending.'),ev('parent','user','Result','Task resumed from the document. Memory recovery remains pending.')]
];
function pause(){clearTimeout(timer);timer=undefined;$('play').textContent='Play demo';}
function next(){if(waiting||cursor>=steps.length){pause();return;}const e=steps[cursor++],row=append(e);if(e.question){pause();waiting=true;$('prompt').textContent='Choose below to return a decision through the parent.';const choices=document.createElement('div');choices.className='choices';for(const label of ['Filtered rows','All accessible rows']){const b=document.createElement('button');b.textContent=label;b.onclick=()=>{choices.remove();waiting=false;append(ev('user','parent','User decision',label));steps[cursor]={...steps[cursor],text:`Confirmed scope: ${label}. Update the ODD task, retain permissions, then continue.`};$('prompt').textContent=label;};choices.append(b)}row.append(choices)}if(cursor===steps.length)pause();}
function reset(){pause();steps=demos[+$('scenario').value].map(e=>({...e}));cursor=0;total=0;waiting=false;seen.clear();$('log').textContent='';$('count').textContent='0 events';$('prompt').textContent='Choose an example and press Play demo.';$('child').textContent='Subagent context will appear after delegation.';graph('user','user');}
function play(){if(timer){pause();return;}if(cursor>=steps.length)reset();function tick(){next();if(!waiting&&cursor<steps.length){$('play').textContent='Pause';timer=setTimeout(tick,+$('speed').value)}}tick()}
$('play').onclick=play;$('step').onclick=()=>{pause();next()};$('reset').onclick=reset;$('scenario').onchange=reset;reset();
const key=location.hash.slice(1);
if(key&&location.protocol!=='file:'){
 for(const id of ['scenario','play','step','reset','speed'])$(id).disabled=true;
 $('connection').textContent='CONNECTING';$('notice').textContent='Live observable events · reply and approve actions in the Gentle terminal';$('prompt').textContent='Send a message in the Gentle terminal.';
 const feed=new EventSource(`/events?key=${encodeURIComponent(key)}`);
 feed.onopen=()=>{$('connection').textContent='LIVE · CONNECTED';$('connection').className='live'};
 feed.addEventListener('mode',event=>{const mode=JSON.parse(event.data).mode;if(mode!=='live'){$('connection').textContent='TEST FEED · SCRIPTED';$('notice').textContent='Synthetic integration test feed — not a real agent session'}});
 feed.addEventListener('gap',()=>{$('notice').textContent='Reconnected; older events exceeded the 500-event buffer.'});
 feed.onmessage=event=>append(JSON.parse(event.data));
 feed.onerror=()=>{$('connection').textContent='DISCONNECTED · RETRYING';$('connection').className='';$('phase').textContent='NO LIVE SIGNAL';$('graph').querySelectorAll('animateMotion').forEach(e=>e.remove())};
}
