(function(){'use strict';const $=id=>document.getElementById(id),E=GentleEngine.esc;let engine=GentleEngine.create(SCENARIOS[0]),speed=1,last=0,painted=-1,expanded=new Set(),autoAll=true;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const labels={user:'Usuario',parent:'Padre',worker:'Subagente',tools:'Herramientas',native:'Motor RDD',memory:'Engram'};
const slots={user:[145,8],parent:[145,87],worker:[25,183],native:[265,183],tools:[25,279],memory:[265,279]};
const paths={ 'user-parent':'M220 57V87','parent-worker':'M180 136V157H100V183','parent-native':'M260 136V157H340V183','worker-tools':'M100 232V279','parent-tools':'M145 112H8V304H25','parent-memory':'M295 112H438V304H415','native-worker':'M265 209H175','native-memory':'M340 232V279' };
function edge(a,b){if(paths[a+'-'+b])return {d:paths[a+'-'+b],reverse:false,key:a+'-'+b};if(paths[b+'-'+a])return {d:paths[b+'-'+a],reverse:true,key:b+'-'+a};return {d:paths['parent-native'],reverse:false,key:'parent-native'}}
function flow(v){let active=edge(...v.e.route);return `<svg class="flow" viewBox="0 0 450 340" aria-label="Flujo activo: ${E(labels[v.e.route[0]])} hacia ${E(labels[v.e.route[1]])}"><defs><marker id="arr" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M0 0L10 5L0 10" fill="#4bd1b1"/></marker></defs>${Object.entries(paths).map(([k,d])=>`<path id="edge-${k}" class="edge ${k===active.key?'active':''}" d="${d}" ${k===active.key?`marker-${active.reverse?'start':'end'}="url(#arr)"`:''}/>`).join('')}${Object.entries(slots).map(([k,[x,y]])=>`<g class="${v.e.route.includes(k)?'active':''}"><rect x="${x}" y="${y}" width="150" height="49" rx="7"/><text x="${x+75}" y="${y+29}" text-anchor="middle">${labels[k]}</text></g>`).join('')}${reduced?'':`<circle class="packet" r="4"><animateMotion dur="1.6s" repeatCount="indefinite" path="${active.d}" ${active.reverse?'keyPoints="1;0" keyTimes="0;1" calcMode="linear"':''}/></circle>`}</svg>`}
function card(row,v){if(row.type==='user'||row.type==='parent')return `<article class="row message ${row.type}"><div class="who">${row.type==='user'?'TÚ':'PADRE · GENTLE SHELL'}</div><p>${E(row.text)}</p></article>`;
if(row.type==='question'){const live=row.id===v.e.id;return `<article class="row question"><div class="who">PADRE → USUARIO · DECISIÓN</div><p>${E(row.text)}</p><div class="options">${row.options.map(o=>`<button data-answer="${E(o.value)}" class="${engine.state.answers[row.key]===o.value&&(!live||engine.state.confirmed[row.key])?'selected':''}" ${live?'':'disabled'}>${E(o.label)}</button>`).join('')}</div><small>${E(row.note||'La elección vuelve al padre antes de continuar.')}</small></article>`}
if(row.type==='end')return `<div class="row ending">✓ ${E(row.text)}</div>`;
const r=row.result||row,status=row.result?(r.status||'completed'):row.type==='delegate'?'running':row.type==='tool'?'completed':row.status||'completed';const title=row.type==='delegate'?(row.result?'Agent result':'Agent task'):row.actor;const actor=row.type==='delegate'?' · '+row.actor:'';const det={...(row.details||{}),...(r.details||{})};return `<fieldset class="row tool ${status==='completed'?'result':''} ${status==='interaction_required'?'needs':''}"><legend>${E(title)}${E(actor)} <span class="state">· ${E(status)}</span></legend><div class="summary">${E(r.text)}</div>${Object.keys(det).length?`<details data-detail="${row.id}" ${expanded.has(row.id)?'open':''}><summary>Ver contrato y evidencia</summary><pre>${E(JSON.stringify(det,null,2))}</pre></details>`:''}</fieldset>`}
function render(){const v=engine.view();$('log').innerHTML=v.rows.map(r=>card(r,v)).join('')||'<div class="empty">La sesión espera el mensaje del usuario…</div>';$('composerText').textContent=v.composer|| (v.waiting?'Elige una opción para continuar.':v.done?'Ejemplo terminado. Puedes repetirlo o elegir otro.':'');$('promptStatus').textContent=v.waiting?'Esperando decisión':v.e.type==='user'?'Usuario escribiendo…':engine.state.playing?'Agente trabajando':'Pausado';$('phase').textContent=v.e.phase;$('step').textContent=`${v.index+1} / ${v.count}`;$('seek').max=v.count-1;$('seek').value=v.index;$('play').textContent=engine.state.playing?'Pausar':'Reproducir';if($('flow').dataset.event!==v.e.id){$('flow').innerHTML=flow(v);$('flow').dataset.event=v.e.id}const flowSvg=$('flow').querySelector('svg');if(engine.state.playing)flowSvg.unpauseAnimations?.();else flowSvg.pauseAnimations?.();$('handoff').textContent=`${labels[v.e.route[0]]} → ${labels[v.e.route[1]]}`;$('childLog').innerHTML=v.childRows.length?v.childRows.slice(-4).map(r=>`<p><b>${E(r.actor)}</b><br>${E(r.text)}</p>`).join(''):'<span class="empty">El trabajo del subagente aparecerá aquí cuando el padre delegue.</span>';$('explain').textContent=v.e.note||({child:'Trabajo en el contexto del hijo. El resultado vuelve al padre; no es una nueva conversación independiente con el usuario.',delegate:'El padre entrega una misión acotada, criterios y contexto. Sigue siendo responsable del resultado.',result:'El padre recibe un estado estructurado. Una decisión humana se devuelve como interaction_required.',question:'En modo cine se usa la respuesta del guion. Activa «Decidir yo» para elegir y recorrer la alternativa.',tool:'Salida de herramienta simulada. Las tarjetas pueden expandirse para ver el contrato o la evidencia.',user:'La petición se escribe en la barra y entra a la sesión del padre.',parent:'Respuesta visible del padre: acciones y resultados. No representa razonamiento privado.'}[v.e.type]||'El resultado de la simulación no ejecuta acciones sobre un repositorio real.');$('clock').textContent=fmt(v.elapsed)+' / '+fmt(v.total);document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{engine.answer(b.dataset.answer);render()});document.querySelectorAll('details[data-detail]').forEach(d=>d.ontoggle=()=>d.open?expanded.add(d.dataset.detail):expanded.delete(d.dataset.detail));$('log').scrollTop=$('log').scrollHeight;$('childLog').scrollTop=$('childLog').scrollHeight;}
function fmt(t){return Math.floor(t/60)+':'+String(Math.floor(t%60)).padStart(2,'0')}
function load(i,play=false){const manual=engine.state.manual;engine=GentleEngine.create(SCENARIOS[i]);engine.state.manual=manual;engine.state.playing=play;expanded.clear();$('case').value=i;render()}
$('case').innerHTML=SCENARIOS.map((s,i)=>`<option value="${i}">${E(s.title)}</option>`).join('');$('case').onchange=()=>load(+$('case').value);$('play').onclick=()=>{if(engine.view().done){engine.reset()}if(!engine.state.waiting)engine.state.playing=!engine.state.playing;render()};$('prev').onclick=()=>{engine.seek(engine.state.index-1);render()};$('next').onclick=()=>{if(engine.current().type==='question'&&engine.state.manual&&!engine.state.confirmed[engine.current().key]){engine.state.waiting=true;engine.state.playing=false}else engine.seek(engine.state.index+1);render()};$('seek').oninput=()=>{engine.seek(+$('seek').value);render()};$('speed').onchange=()=>speed=+$('speed').value;$('manual').onchange=()=>{engine.state.manual=$('manual').checked;if(!engine.state.manual&&engine.state.waiting){engine.state.waiting=false;engine.state.playing=true}render()};$('all').onchange=()=>autoAll=$('all').checked;$('full').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.querySelector('.app').requestFullscreen?.();$('sources').onclick=()=>$('sourceDialog').showModal();$('closeSources').onclick=()=>$('sourceDialog').close();document.addEventListener('keydown',e=>{if(['INPUT','SELECT','BUTTON'].includes(e.target.tagName))return;if(e.code==='Space'){e.preventDefault();$('play').click()}if(e.code==='ArrowRight')$('next').click();if(e.code==='ArrowLeft')$('prev').click()});document.addEventListener('visibilitychange',()=>{if(document.hidden){engine.state.playing=false;render()}});
function frame(now){const dt=last?Math.min((now-last)/1000,.2):0;last=now;const was=engine.state.playing;engine.tick(dt*speed);if(was&&now-painted>90){render();painted=now}if(was&&engine.view().done&&autoAll){const i=+$('case').value;if(i<SCENARIOS.length-1)load(i+1,true)}requestAnimationFrame(frame)}render();requestAnimationFrame(frame);
window.GentleDemo={load,get engine(){return engine},render};
})();
