from pathlib import Path
import json
S=[]
def scenario(id,title,subtitle,defaults={}):
 d={'id':id,'title':title,'subtitle':subtitle,'defaults':defaults,'events':[]};S.append(d);return d
def e(s,t,actor,text,phase='ODD',route=None,**kw):
 s['events'].append(dict(id=f'{s["id"]}-{len(s["events"])+1}',type=t,actor=actor,text=text,phase=phase,route=route or ['user','parent'],duration=kw.pop('duration',5),**kw))
a=scenario('texto','01 · Un cambio pequeño','Una petición clara. Sin preguntas artificiales.')
e(a,'user','Tú','Corrige «Exportar archibo» en la ayuda del reporte.',duration=5)
e(a,'parent','Padre','Voy a localizar el texto y corregir solo esa palabra.',['ODD'][0],['parent','tools'])
e(a,'tool','read / git diff','docs/reportes.md · localizada la errata. Un archivo pasivo, cambio comprendido.',route=['tools','parent'],details={'ruta':'docs/reportes.md','alcance':'una palabra','estado':'lectura completada'})
e(a,'parent','Padre','Es una corrección pequeña. Puedo hacerla directamente; no necesito delegar ni crear un documento de tareas.',route=['parent','user'])
e(a,'tool','edit','Exportar archibo → Exportar archivo',route=['parent','tools'],details={'archivo':'docs/reportes.md','cambio':'sustitución puntual','TDD':'excepción documental; sin comportamiento ejecutable'})
e(a,'tool','Gentle AI · review assess','completed · passive · lectura estructural · 0 perspectivas de revisión','RDD',['native','parent'],details={'risk':'passive','review_due':False,'review_due_reason':'passive','evidencia':'contenido y diff inspeccionados'})
e(a,'parent','Padre','Corregido. Revisé el texto final y el diff. No cambié el comportamiento del programa.','ODD',['parent','user'])
e(a,'end','Resultado','El usuario pidió un cambio claro. El padre lo resolvió sin inventar preguntas ni lanzar subagentes.',route=['parent','user'],duration=6)
b=scenario('csv','02 · CSV con una duda del worker','Padre ↔ subagente ↔ usuario, TDD, memoria y revisión.',{'scope':'filtrados','review':'yes'})
e(b,'user','Tú','Añade un botón para exportar los reportes a CSV. Usa el flujo actual.',duration=6)
e(b,'parent','Padre','Voy a explorar cómo se construye el reporte. Hay varios archivos involucrados; delego esa exploración.',route=['parent','worker'])
e(b,'delegate','gentle-ai-explore','Mapear reporte, filtros y permisos. Solo lectura. Devolver rutas y decisiones pendientes.',route=['parent','worker'],task='csv-map',details={'agent':'gentle-ai-explore','mode':'background (si política habilitada)','objetivo':'exploración acotada','escritura':'no autorizada','responsable':'padre'})
e(b,'child','gentle-ai-explore','Leo ReportView, ReportViewModel, ReportService, filtros, permisos y pruebas.',route=['worker','tools'],task='csv-map',note='Este trabajo ocurre en el contexto del subagente; el padre no vuelve a leer todo.')
e(b,'result','gentle-ai-explore','completed · 6 archivos inspeccionados. El flujo admite exportación; hay dos alcances posibles.',route=['worker','parent'],task='csv-map',details={'status':'completed','summary':'puntos de integración identificados','decisión':'filtrados o todos los reportes accesibles','files_changed':[]})
e(b,'parent','Padre','La funcionalidad necesita varias tareas. Dejo el objetivo, las restricciones y los criterios en un documento ODD.',route=['parent','memory'])
e(b,'tool','write + mem_save','odd/tasks/export-csv.md guardado; espejo completo en odd/export-csv/tasks. Lectura de comprobación realizada.',route=['memory','parent'],details={'archivo':'odd/tasks/export-csv.md','tareas':['definir alcance','formatear CSV','integrar botón','verificar'],'TDD':'activo por configuración','runner':'dotnet test --filter Csv'})
e(b,'delegate','gentle-ai-worker','Implementar CSV. Leer documento y skills indicadas; respetar superficies permitidas; devolver evidencia.',route=['parent','worker'],task='csv-write',details={'agent':'gentle-ai-worker','tarea':'exportación CSV','allowed_edit_surfaces':['ReportViewModel.cs','CsvExporter.cs','CsvTests.cs'],'TDD':'on · configuración del proyecto','runner':'dotnet test --filter Csv','criterio':'mantener permisos actuales'})
e(b,'child','gentle-ai-worker','Antes de editar encuentro una decisión de producto: exportar lo filtrado o todos los reportes accesibles.',route=['worker','tools'],task='csv-write')
e(b,'result','gentle-ai-worker','interaction_required · necesito una decisión de alcance; no he escrito código.',route=['worker','parent'],task='csv-write',status='interaction_required',details={'status':'interaction_required','files_changed':[],'interaction_required':{'question':'¿Qué registros debe incluir el CSV?','reason':'ambas rutas existen y cambian el resultado','options':['Solo los filtrados','Todos los accesibles'],'unblock_response':'alcance elegido por el usuario'}})
e(b,'question','Padre','El worker encontró dos comportamientos posibles. ¿Qué registros debe incluir el CSV?',route=['parent','user'],key='scope',options=[{'value':'filtrados','label':'Solo los filtrados'},{'value':'todos','label':'Todos los accesibles'}],note='El padre transmite la decisión; el subagente no elige por el usuario.',duration=7)
e(b,'user','Tú','Quiero {{scopeLabel}}. Mantén los permisos actuales.',route=['user','parent'])
e(b,'tool','ODD · actualizar intención','Alcance aceptado: {{scopeLabel}}. Actualizo tareas y espejo antes de continuar.',route=['parent','memory'])
e(b,'delegate','gentle-ai-worker','Continuar con el alcance confirmado: {{scopeLabel}}. Mismo contrato, superficies y runner.',route=['parent','worker'],task='csv-write-2',details={'respuesta':'{{scopeLabel}}','estado':'nueva ejecución acotada con contexto actualizado','documento':'odd/tasks/export-csv.md','TDD':'activo'})
e(b,'child','gentle-ai-worker','RED · escribo y ejecuto un test: exportar {{scopeLabel}}. Falla por el comportamiento ausente.','TDD',['worker','tools'],task='csv-write-2',details={'comando':'dotnet test --filter Csv','RED':'fallo esperado observado','nota':'resultado de demostración, no ejecución real'})
e(b,'child','gentle-ai-worker','GREEN · implemento lo mínimo y repito el test. El comportamiento esperado pasa.','TDD',['tools','worker'],task='csv-write-2')
e(b,'child','gentle-ai-worker','TRIANGULATE · comillas, comas y lista vacía. REFACTOR · separo formateador y vuelvo a probar.','TDD',['worker','tools'],task='csv-write-2',details={'casos':['selección de registros','escape de comillas','lista vacía'],'resultado':'pruebas focalizadas verdes'})
e(b,'wait','Runtime de Pi','agent_end conserva la respuesta; el padre espera agent_settled antes de tratar la tarea como terminada.',route=['worker','parent'],task='csv-write-2',note='En background el resultado llega por evento. No se simula polling de finalización.')
e(b,'result','gentle-ai-worker','completed · exportación implementada y pruebas focalizadas reportadas. Resultado entregado al padre.',route=['worker','parent'],task='csv-write-2',details={'status':'completed','files_changed':['ReportViewModel.cs','CsvExporter.cs','CsvTests.cs'],'tdd_evidence':['RED observado','GREEN observado','casos alternos y refactor verdes'],'validation':['dotnet test --filter Csv: pasa en la simulación'],'risks':[]})
e(b,'parent','Padre','Compruebo el resultado y una prueba reportada. Registro evidencia y progreso; el commit de unidad requiere autorización del repo.',route=['parent','tools'],details={'autorización del ejemplo':'commits de unidad permitidos','push / PR':'aún no autorizados'})
e(b,'tool','Gentle AI · review assess','completed · medium · tramo ilustrativo de 420 líneas · review_due: true','RDD',['native','parent'],details={'risk':'medium','changed_lines':420,'review_due':True,'review_due_reason':'slice_budget_reached','next_transition':'continuación nativa, sin inventar tokens'})
e(b,'tool','Gentle AI · STATUS / START','Se sigue la transición nativa. El candidato se congela con su identidad; se presenta el consentimiento aplicable.','RDD',['parent','native'],details={'binding':'lineage + revision + target emitidos por el motor','contexto':'árboles inmutables','nota':'no se usan identificadores falsos ejecutables'})
e(b,'question','Padre','Este candidato requiere una revisión focalizada. ¿Quieres ejecutarla ahora?','RDD',['parent','user'],key='review',options=[{'value':'yes','label':'Revisar ahora'},{'value':'no','label':'Ahora no'}],note='Opciones didácticas: no reproducen un sobre nativo literal.',duration=7)
e(b,'user','Tú','{{reviewLabel}}.','RDD',['user','parent'])
e(b,'tool','Gentle AI · review','running · una perspectiva sobre el candidato congelado. El host Pi transporta el resultado al motor.','RDD',['native','worker'],when={'review':'yes'},details={'perspectivas':1,'fuente':'candidato congelado','autoridad':'motor nativo'})
e(b,'tool','Gentle AI · resultado + ACK','completed · aprobado en el ejemplo; ACK exacto consumido. La revisión no hace push ni abre PR.','RDD',['native','parent'],when={'review':'yes'})
e(b,'tool','Gentle AI · verificación alternativa','Revisión declinada para este candidato. Riesgo medio: conservar evidencia del escritor y comprobación del padre.','RDD',['native','parent'],when={'review':'no'},details={'review':'no ejecutado','modo global':'sin cambio','verificador extra':'si el escritor usa perfil mini/bajo esfuerzo'})
e(b,'parent','Padre','Listo: el CSV exporta {{scopeLabel}} y respeta permisos. Pruebas reportadas y documento actualizado. {{reviewOutcome}}',route=['parent','user'])
e(b,'end','Resultado','Una duda del worker viajó al padre y al usuario. La respuesta volvió al worker con contexto; el padre integró evidencia y cierre.',duration=7)
c=scenario('auth','03 · Riesgo alto y corrección','La revisión encuentra un defecto; el padre conduce un arreglo acotado.',{'review':'yes'})
e(c,'user','Tú','Evita que un usuario vea reportes de otra empresa. Puedes hacer commits de esta tarea, pero no publiques.')
e(c,'parent','Padre','Exploro autorización, consulta y caché. El alcance es aislamiento entre empresas; una edición pequeña puede tener alto riesgo.',route=['parent','tools'])
e(c,'tool','write + mem_save','ODD registrado: criterio de aislamiento, superficies acotadas, pruebas y siguiente paso.',route=['parent','memory'])
e(c,'delegate','gentle-ai-worker','Corregir aislamiento. TDD activo. Probar acceso propio, ajeno y ausencia de tenant.',route=['parent','worker'],task='auth-write',details={'surfaces':['Authorization.cs','ReportService.cs','TenantTests.cs'],'criterio':'usuario de A no accede a B','runner':'dotnet test --filter Tenant','alcance':'sin rediseño general'})
e(c,'child','gentle-ai-worker','RED reproduce acceso cruzado; GREEN añade validación; TRIANGULATE cubre casos alternos; REFACTOR mantiene pruebas verdes.','TDD',['worker','tools'],task='auth-write',duration=7)
e(c,'result','gentle-ai-worker','completed · validación de empresa añadida; evidencia focalizada devuelta al padre.',route=['worker','parent'],task='auth-write',details={'status':'completed','validation':['dotnet test --filter Tenant: pasa en el ejemplo'],'risk':'la prueba focalizada no demuestra ausencia de otros defectos'})
e(c,'tool','Gentle AI · review assess','completed · high · señal de autorización · review_due: true, aunque el diff sea pequeño.','RDD',['native','parent'])
e(c,'tool','Gentle AI · STATUS / START','Candidato congelado; se respeta el consentimiento concedido para este ejemplo. Plan de cuatro perspectivas.','RDD',['parent','native'])
e(c,'delegate','4R · Risk / Resilience / Readability / Reliability','running · cuatro revisores sobre la misma versión, en paralelo cuando lo admite el runtime.','RDD',['native','worker'],task='four-r',details={'Risk':'abuso y exposición','Resilience':'fallos y recuperación','Readability':'claridad','Reliability':'corrección','contexto':'misma identidad congelada'})
e(c,'child','Revisor · Risk','Hallazgo: la clave de caché no incluye la empresa. Dos tenants podrían compartir una respuesta.','RDD',['worker','tools'],task='four-r')
e(c,'result','4R','Hallazgos y evidencias vuelven al motor nativo. Una afirmación aún debe contrastarse.','RDD',['worker','native'],task='four-r')
e(c,'tool','Gentle AI · refutación','El refutador contrasta la afirmación; el caso de caché queda sustentado en este ejemplo.','RDD',['native','worker'],details={'claim':'caché sin tenant','evidencia':'misma clave con empresas distintas','resultado':'defecto sustentado'})
e(c,'parent','Padre','Hay un defecto dentro del alcance: la clave de caché. Aplico una corrección acotada siguiendo la transición nativa.','RDD',['parent','worker'])
e(c,'delegate','Corrección acotada','Un lote: incluir tenant en la clave y añadir el caso de regresión. Respetar el presupuesto y superficies nativos.','RDD',['parent','worker'],task='fix-cache')
e(c,'child','Worker de corrección','Pruebo dos empresas con el mismo ID, reproduzco la fuga y corrijo la clave. La prueba focalizada pasa.','TDD',['worker','tools'],task='fix-cache')
e(c,'result','Worker de corrección','completed · corrección y evidencia devueltas. El candidato corregido tiene una nueva identidad.','RDD',['worker','parent'],task='fix-cache')
e(c,'tool','Gentle AI · validación dirigida','Comprueba aislamiento original y regresiones de la corrección sobre los árboles correctos.','RDD',['native','worker'],details={'criterio original':'acceso ajeno bloqueado','regresión':'acceso propio conservado','límite':'sin inspección no existe veredicto'})
e(c,'tool','Gentle AI · resultado + ACK','completed · aprobado en el ejemplo; ACK consumido. No se inicia otra ronda de corrección.','RDD',['native','parent'])
e(c,'parent','Padre','El aislamiento quedó corregido, incluida la clave de caché. Te entrego evidencia y commits de la tarea. No he publicado.',route=['parent','user'])
e(c,'end','Resultado','El padre mantuvo el hilo. La revisión no sustituyó las pruebas y su aprobación no autorizó publicar.',duration=6)
d=scenario('resume','04 · Retomar sin memoria disponible','Interrupción, estado real, relanzamiento y TDD desactivado.')
e(d,'user','Tú','Continúa la exportación que dejamos ayer. No actives TDD; usa los checks configurados.')
e(d,'tool','read + mem_search','Documento ODD recuperado. Engram no está disponible: el espejo queda pendiente.',route=['memory','parent'],details={'archivo':'odd/tasks/export-csv.md','memoria':'no disponible','acción':'no inventar sincronización'})
e(d,'parent','Padre','Conservo el documento local y comprobaré el código actual. La tarea del worker que estaba corriendo no se recupera como si siguiera activa.',route=['parent','user'])
e(d,'tool','git diff + configuración','Conciliados los cambios válidos. TDD: off por elección actual. Runner de comprobación identificado.',route=['tools','parent'])
e(d,'delegate','gentle-ai-worker','Nueva ejecución para la tarea pendiente, con contexto reconciliado. TDD off; checks funcionales obligatorios.',route=['parent','worker'],task='resume-new',details={'tarea anterior':'interrumpida, no reclamada como viva','tarea nueva':'contexto explícito','TDD':'off · elección del usuario','runner':'dotnet test --filter Csv'})
e(d,'child','gentle-ai-worker','Termino el comportamiento pendiente y ejecuto los checks focalizados. No declaro un RED/GREEN que no ocurrió.','TDD',['worker','tools'],task='resume-new')
e(d,'result','gentle-ai-worker','completed · resultado y validación devueltos al padre. Sin ciclo TDD inventado.',route=['worker','parent'],task='resume-new')
e(d,'tool','Gentle AI · review mode / assess','Modo efectivo: off en este ejemplo. Se evalúa riesgo sin iniciar revisión nativa.','RDD',['native','parent'])
e(d,'tool','Verificación alternativa','Riesgo medio y escritor con perfil mini: añadir gentle-ai-verify; el padre conserva su comprobación puntual.','RDD',['parent','worker'])
e(d,'delegate','gentle-ai-verify','Verificar el cambio con contexto fresco y devolver comandos observados.',route=['parent','worker'],task='verify-resume')
e(d,'result','gentle-ai-verify','completed · comprobaciones pasan en la simulación. Se reporta el espejo de Engram todavía pendiente.',route=['worker','parent'],task='verify-resume')
e(d,'parent','Padre','La exportación está comprobada. Actualicé el documento local; Engram queda pendiente. RDD no se ejecutó porque estaba desactivado.',route=['parent','user'])
e(d,'end','Resultado','Reanudar significa reconciliar evidencia y relanzar lo pendiente; no fingir que el worker sigue vivo.',duration=6)
Path(__file__).with_name('scenarios.json').write_text(json.dumps(S,ensure_ascii=False,indent=2))
print([(s['id'],len(s['events'])) for s in S])
